/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polypro.ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import polypro.dao.NhanVienDAO;
import polypro.helper.DialogHelper;
import polypro.helper.JdbcHelper;
import polypro.helper.ShareHelper;
import polypro.model.NhanVien;

/**
 *
 * @author PC
 */
public class DangNhapJDialog extends javax.swing.JDialog {

    /**
     * Creates new form DangNhapJDialog
     */
    public DangNhapJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void login(){
        NhanVienDAO dao = new NhanVienDAO();
        String user = txtUser.getText();
        String pass = new String(txtPass.getPassword());
        try {
            NhanVien nhanvien = dao.findByID(user);
            if (nhanvien != null) {
                String pass2 = nhanvien.getMatkhau();
                if (pass.equals(pass2)) {
                    ShareHelper.USER = nhanvien;
                    DialogHelper.alert(this, "Đăng Nhập thành công ^^!");
                    this.dispose();
                }else{
                    DialogHelper.alert(this, "Sai mật khẩu ^^!");
                }
            }else{
                DialogHelper.alert(this, "Sai tài khoản ^^!");
            }
            
        } catch (Exception e) {
            DialogHelper.alert(this, "Failed ^^!");
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LG = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        BGL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        P = new javax.swing.JLabel();
        U = new javax.swing.JLabel();
        SPUser = new javax.swing.JSeparator();
        SPPass = new javax.swing.JSeparator();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        DN = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnQuenMK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        LG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Login/icons8_security_cameras_127px.png"))); // NOI18N
        jPanel1.add(LG);
        LG.setBounds(10, 30, 120, 100);

        Title.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Login/ĐĂNG NHẬP.png"))); // NOI18N
        jPanel1.add(Title);
        Title.setBounds(210, 0, 190, 40);

        BGL.setBackground(new java.awt.Color(255, 255, 255));
        BGL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Login/Rectangle 1.png"))); // NOI18N
        jPanel1.add(BGL);
        BGL.setBounds(-4, 0, 144, 163);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Login/icons8_unlock_26px.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 80, 20, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Login/icons8_contacts_64px.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 40, 20, 30);

        P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Login/Rectangle 3.png"))); // NOI18N
        jPanel1.add(P);
        P.setBounds(170, 80, 40, 30);

        U.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Login/Rectangle 3.png"))); // NOI18N
        jPanel1.add(U);
        U.setBounds(170, 40, 40, 30);
        jPanel1.add(SPUser);
        SPUser.setBounds(220, 70, 180, 10);
        jPanel1.add(SPPass);
        SPPass.setBounds(220, 110, 180, 10);

        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtUser.setText("Nhập tài khoản");
        txtUser.setBorder(null);
        txtUser.setMargin(new java.awt.Insets(1, 1, 1, 1));
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        jPanel1.add(txtUser);
        txtUser.setBounds(220, 40, 180, 30);

        txtPass.setText("xxxxxxxxxx");
        txtPass.setBorder(null);
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPassMouseClicked(evt);
            }
        });
        jPanel1.add(txtPass);
        txtPass.setBounds(220, 82, 180, 30);

        DN.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        DN.setText("Đăng Nhập");
        DN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(DN);
        DN.setBounds(240, 130, 70, 50);

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("Kết Thúc");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(Exit);
        Exit.setBounds(340, 130, 80, 50);

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Login/Rectangle 11.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(310, 140, 110, 30);

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Login/Rectangle 10.png"))); // NOI18N
        btnLogin.setAutoscrolls(true);
        btnLogin.setBorder(null);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setFocusCycleRoot(true);
        btnLogin.setSelected(true);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin);
        btnLogin.setBounds(230, 140, 90, 30);

        btnQuenMK.setText("Quên mật khẩu");
        btnQuenMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuenMKActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuenMK);
        btnQuenMK.setBounds(10, 170, 120, 25);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        boolean result = DialogHelper.confirm(this, "Bạn có muốn thoát không");
        if (result == true) {
            System.exit(0);
        }else{
            
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if (isvalid()) {
            this.login();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        // TODO add your handling code here:
        txtUser.setText("");
    }//GEN-LAST:event_txtUserMouseClicked

    private void txtPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMouseClicked
        // TODO add your handling code here:
        txtPass.setText("");
    }//GEN-LAST:event_txtPassMouseClicked

    private void btnQuenMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuenMKActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new QuenMatKhauJFrame().setVisible(true);
    }//GEN-LAST:event_btnQuenMKActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhapJDialog dialog = new DangNhapJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGL;
    private javax.swing.JLabel DN;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel LG;
    private javax.swing.JLabel P;
    private javax.swing.JSeparator SPPass;
    private javax.swing.JSeparator SPUser;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel U;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnQuenMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    boolean isvalid(){
        if (txtUser.getText().length() == 0) {
            DialogHelper.alert(this, "Vui lòng nhập tên đăng nhập!!");
            txtUser.requestFocus();
            return false;
        }
        if (txtPass.getText().length() == 0) {
            DialogHelper.alert(this, "Vui lòng nhập mật khẩu");
            txtPass.requestFocus();
            return false;
        }
        return true;
    }
}
