/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polypro.ui;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import polypro.dao.NguoiHocDAO;
import polypro.dao.NhanVienDAO;
import polypro.helper.DateHelper;
import polypro.helper.DialogHelper;
import polypro.model.NguoiHoc;
import polypro.model.NhanVien;

/**
 *
 * @author PC
 */
public class NguoiHocJFrame extends javax.swing.JFrame {

    NguoiHocDAO nhdao = new NguoiHocDAO();
    NhanVienDAO nvdao = new NhanVienDAO();
    int index = 0;

    /**
     * Creates new form NguoiHocJFrame
     */
    public NguoiHocJFrame() {
        initComponents();
        init();
    }

    void back() {
        this.dispose();
    }

    void init() {
        setStatus(true);
        tblNguoiHoc.setRowSelectionInterval(index, index);
        this.setLocationRelativeTo(null);
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlNguoiHoc = new javax.swing.JTabbedPane();
        pnlCapNhat = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        txtMaNH = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        rbtnNam = new javax.swing.JRadioButton();
        rbtnNu = new javax.swing.JRadioButton();
        txtSoDT = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        txtNgayDK = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArena = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        txtNgayS = new javax.swing.JTextField();
        pnlDanhSach = new javax.swing.JPanel();
        Spator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguoiHoc = new javax.swing.JTable();
        txtHT = new javax.swing.JTextField();
        btnSreach = new javax.swing.JButton();
        lblArrow = new javax.swing.JLabel();
        LogoT = new javax.swing.JLabel();
        TitleTop = new javax.swing.JLabel();
        btnThongke = new javax.swing.JLabel();
        btnQuanly = new javax.swing.JLabel();
        btnHuongdan = new javax.swing.JLabel();
        btnDangxuat = new javax.swing.JLabel();
        BtnExit = new javax.swing.JButton();
        BGRT = new javax.swing.JLabel();
        BGRB = new javax.swing.JLabel();
        BGLT = new javax.swing.JLabel();
        BGLB = new javax.swing.JLabel();
        BGButton = new javax.swing.JLabel();
        BGLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNguoiHoc.setBackground(new java.awt.Color(0, 255, 51));
        pnlNguoiHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlNguoiHoc.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        pnlCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        pnlCapNhat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 17.png"))); // NOI18N
        btnThem.setBorder(null);
        btnThem.setContentAreaFilled(false);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        btnSua.setBackground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 18.png"))); // NOI18N
        btnSua.setBorder(null);
        btnSua.setContentAreaFilled(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 19.png"))); // NOI18N
        btnXoa.setBorder(null);
        btnXoa.setContentAreaFilled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 20.png"))); // NOI18N
        btnMoi.setBorder(null);
        btnMoi.setContentAreaFilled(false);
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 21.png"))); // NOI18N
        btnFirst.setBorder(null);
        btnFirst.setContentAreaFilled(false);
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 22.png"))); // NOI18N
        btnPrev.setBorder(null);
        btnPrev.setContentAreaFilled(false);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 23.png"))); // NOI18N
        btnNext.setBorder(null);
        btnNext.setContentAreaFilled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 24.png"))); // NOI18N
        btnLast.setBorder(null);
        btnLast.setContentAreaFilled(false);
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        txtMaNH.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtMaNH.setForeground(new java.awt.Color(255, 0, 0));
        txtMaNH.setBorder(null);
        txtMaNH.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        pnlCapNhat.add(txtMaNH, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, -1));

        txtHoten.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtHoten.setBorder(null);
        pnlCapNhat.add(txtHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 190, -1));

        rbtnNam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnNam);
        rbtnNam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtnNam.setText("Nam");
        pnlCapNhat.add(rbtnNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        rbtnNu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnNu);
        rbtnNu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtnNu.setText("Nữ");
        pnlCapNhat.add(rbtnNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        txtSoDT.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtSoDT.setBorder(null);
        pnlCapNhat.add(txtSoDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 190, -1));

        txtDiachi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtDiachi.setBorder(null);
        pnlCapNhat.add(txtDiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 190, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtEmail.setBorder(null);
        pnlCapNhat.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 190, -1));

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtMaNV.setForeground(new java.awt.Color(0, 0, 255));
        txtMaNV.setBorder(null);
        txtMaNV.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        pnlCapNhat.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 150, -1));

        txtNgayDK.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtNgayDK.setBorder(null);
        pnlCapNhat.add(txtNgayDK, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 150, -1));

        txtArena.setColumns(20);
        txtArena.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtArena.setRows(5);
        jScrollPane2.setViewportView(txtArena);

        pnlCapNhat.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 480, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Mã người học:");
        pnlCapNhat.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên:");
        pnlCapNhat.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Họ và tên:");
        pnlCapNhat.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Giới tính:");
        pnlCapNhat.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Địa chỉ:");
        pnlCapNhat.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Email:");
        pnlCapNhat.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Số điện thoại:");
        pnlCapNhat.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Ngày đăng ký:");
        pnlCapNhat.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Ghi chú:");
        pnlCapNhat.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Ngày Sinh:");
        pnlCapNhat.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));
        pnlCapNhat.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 150, 10));
        pnlCapNhat.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 150, 10));
        pnlCapNhat.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 190, 10));
        pnlCapNhat.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 190, 10));
        pnlCapNhat.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 190, 10));
        pnlCapNhat.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 190, 10));
        pnlCapNhat.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 150, 10));
        pnlCapNhat.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 150, 10));

        txtNgayS.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtNgayS.setBorder(null);
        txtNgayS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySActionPerformed(evt);
            }
        });
        pnlCapNhat.add(txtNgayS, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 150, -1));

        pnlNguoiHoc.addTab("Cập Nhật", pnlCapNhat);

        pnlDanhSach.setBackground(new java.awt.Color(255, 255, 255));
        pnlDanhSach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlDanhSach.add(Spator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 540, 10));

        tblNguoiHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NH", "Họ và tên", "Giới tính", "Địa Chỉ", "Ngày sinh", "Điện thoại", "Email", "Mã NV", "Ngày ĐK", "Ghi Chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNguoiHoc.setGridColor(new java.awt.Color(0, 0, 255));
        tblNguoiHoc.setSelectionBackground(new java.awt.Color(0, 0, 255));
        tblNguoiHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNguoiHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNguoiHoc);
        if (tblNguoiHoc.getColumnModel().getColumnCount() > 0) {
            tblNguoiHoc.getColumnModel().getColumn(9).setMinWidth(0);
            tblNguoiHoc.getColumnModel().getColumn(9).setPreferredWidth(0);
            tblNguoiHoc.getColumnModel().getColumn(9).setMaxWidth(0);
        }

        pnlDanhSach.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, 591, 330));

        txtHT.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtHT.setText("Nhập tên người học");
        txtHT.setBorder(null);
        txtHT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHTMouseClicked(evt);
            }
        });
        pnlDanhSach.add(txtHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 400, 30));

        btnSreach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/icons8_search_database_100px.png"))); // NOI18N
        btnSreach.setContentAreaFilled(false);
        btnSreach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSreachActionPerformed(evt);
            }
        });
        pnlDanhSach.add(btnSreach, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, -1, -1, 50));

        lblArrow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/icons8_right_40px.png"))); // NOI18N
        pnlDanhSach.add(lblArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 30));

        pnlNguoiHoc.addTab("Danh Sách", pnlDanhSach);

        getContentPane().add(pnlNguoiHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 620, 440));

        LogoT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/icons8_java_48px.png"))); // NOI18N
        getContentPane().add(LogoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 100, 100));

        TitleTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/HỆ THỐNG QUẢN LÝ ĐÀO TẠO.png"))); // NOI18N
        getContentPane().add(TitleTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        btnThongke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 10.png"))); // NOI18N
        btnThongke.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongkeMouseClicked(evt);
            }
        });
        getContentPane().add(btnThongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 300, -1));

        btnQuanly.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuanly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 6.png"))); // NOI18N
        btnQuanly.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnQuanly, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        btnHuongdan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 3.png"))); // NOI18N
        btnHuongdan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnHuongdan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        btnDangxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 4.png"))); // NOI18N
        btnDangxuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnDangxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        BtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/Left.png"))); // NOI18N
        BtnExit.setContentAreaFilled(false);
        BtnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 535, -1, 50));

        BGRT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BGRT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 7.png"))); // NOI18N
        getContentPane().add(BGRT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        BGRB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BGRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 8.png"))); // NOI18N
        getContentPane().add(BGRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, -1, 30));

        BGLT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 1.png"))); // NOI18N
        BGLT.setToolTipText("");
        getContentPane().add(BGLT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BGLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BGLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 11.png"))); // NOI18N
        getContentPane().add(BGLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 530, 320, 60));

        BGButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BGButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 9.png"))); // NOI18N
        getContentPane().add(BGButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 300, 390));

        BGLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 5.png"))); // NOI18N
        getContentPane().add(BGLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeMouseClicked
        // TODO add your handling code here:
        new MainFrame().setEnabled(true);

    }//GEN-LAST:event_btnThongkeMouseClicked

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_BtnExitActionPerformed

    private void txtNgaySActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (checkMaNH() && checkBirthDay() && checkGmail() && checkPhone()) {
            insert();
        }
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (checkBirthDay() && checkGmail() && checkPhone()) {
            update();
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void tblNguoiHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguoiHocMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            index = tblNguoiHoc.rowAtPoint(evt.getPoint());
            txtMaNH.setEnabled(false);
            txtMaNV.setEnabled(false);
            if (index >= 0) {
                edit();
                pnlNguoiHoc.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_tblNguoiHocMouseClicked

    private void txtHTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHTMouseClicked
        // TODO add your handling code here:
        txtHT.setText("");
    }//GEN-LAST:event_txtHTMouseClicked

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        this.index = 0;
        this.edit();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        this.index--;
        this.edit();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        this.index++;
        this.edit();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        this.index = tblNguoiHoc.getRowCount() - 1;
        this.edit();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnSreachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSreachActionPerformed
        // TODO add your handling code here:
        find();
    }//GEN-LAST:event_btnSreachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NguoiHocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NguoiHocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NguoiHocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NguoiHocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NguoiHocJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGButton;
    private javax.swing.JLabel BGLB;
    private javax.swing.JLabel BGLT;
    private javax.swing.JLabel BGLogo;
    private javax.swing.JLabel BGRB;
    private javax.swing.JLabel BGRT;
    private javax.swing.JButton BtnExit;
    private javax.swing.JLabel LogoT;
    private javax.swing.JSeparator Spator2;
    private javax.swing.JLabel TitleTop;
    private javax.swing.JLabel btnDangxuat;
    private javax.swing.JButton btnFirst;
    private javax.swing.JLabel btnHuongdan;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JLabel btnQuanly;
    private javax.swing.JButton btnSreach;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel btnThongke;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lblArrow;
    private javax.swing.JPanel pnlCapNhat;
    private javax.swing.JPanel pnlDanhSach;
    private javax.swing.JTabbedPane pnlNguoiHoc;
    private javax.swing.JRadioButton rbtnNam;
    private javax.swing.JRadioButton rbtnNu;
    private javax.swing.JTable tblNguoiHoc;
    private javax.swing.JTextArea txtArena;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHT;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMaNH;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgayDK;
    private javax.swing.JTextField txtNgayS;
    private javax.swing.JTextField txtSoDT;
    // End of variables declaration//GEN-END:variables

    void load() {
        DefaultTableModel model = (DefaultTableModel) tblNguoiHoc.getModel();
        model.setRowCount(0);
        try {
            List<NguoiHoc> list = nhdao.Select();
            if (list != null) {
                for (NguoiHoc nh : list) {
                    Object[] row = {
                        nh.getMaNH(),
                        nh.getHoTen(),
                        nh.getGioitinh() ? "Nam" : "Nữ",
                        nh.getDiachi(),
                        nh.getNgaySinh(),
                        nh.getSoDT(),
                        nh.getEmail(),
                        nh.getMaNV(),
                        nh.getNgayDK(),
                        nh.getGioitinh()
                    };
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void clear() {
        txtMaNH.setEnabled(true);
        txtMaNV.setEnabled(true);
        btnThem.setEnabled(true);
        txtMaNH.setText("");
        txtHoten.setText("");
        txtDiachi.setText("");
        rbtnNam.isSelected();
        txtNgayS.setText("");
        txtSoDT.setText("");
        txtEmail.setText("");
        txtMaNV.setText("");
        txtNgayDK.setText("");
        txtArena.setText("");
        setStatus(true);
    }

    void insert() {
        NguoiHoc modelnh = getModel();
        NhanVien modelnv = new NhanVien();
        modelnv = nvdao.findByID(txtMaNV.getText());
        if (modelnv != null) {
            try {
                nhdao.Insert(modelnh);
                load();
                clear();
                DialogHelper.alert(this, "Thêm người học thành công");
            } catch (Exception e) {
                e.printStackTrace();
                DialogHelper.alert(this, "Thêm người học không thành công");
            }
        } else {
            DialogHelper.alert(this, "Mã nhân viên không tồn tại!!");
        }
    }

    void update() {
        NguoiHoc modelnh = getModel();
        try {
            nhdao.Update(modelnh);
            int year = modelnh.getNgaySinh().getYear();
            load();
            clear();
            DialogHelper.alert(this, "Cập nhật thông tin người học thành công");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void delete() {
        if (DialogHelper.confirm(this, "Bạn có muốn xoá không?")) {
            String manh = txtMaNH.getText();
            if (manh != null) {
                try {
                    nhdao.Delete(manh);
                    load();
                    clear();
                    DialogHelper.alert(this, "Xoá người học thành công");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }

    void find() {
        DefaultTableModel model = (DefaultTableModel) tblNguoiHoc.getModel();
        model.setRowCount(0);
        String ht = txtHT.getText();
        if (ht != null) {
            try {
                List<NguoiHoc> list = nhdao.SelectByKeyword(ht);
                for (NguoiHoc nh : list) {
                    Object[] row = {
                        nh.getMaNH(),
                        nh.getHoTen(),
                        nh.getGioitinh() ? "Nam" : "Nữ",
                        nh.getDiachi(),
                        nh.getNgaySinh(),
                        nh.getSoDT(),
                        nh.getEmail(),
                        nh.getMaNV(),
                        nh.getNgayDK()};
                    model.addRow(row);
                }
            } catch (Exception e) {

            }

        }
    }

    NguoiHoc getModel() {
        NguoiHoc model = new NguoiHoc();
        model.setMaNH(txtMaNH.getText());
        model.setHoTen(txtHoten.getText());
        model.setDiachi(txtDiachi.getText());
        model.setGioitinh(rbtnNam.isSelected());
        model.setNgaySinh(DateHelper.toDate(txtNgayS.getText(), "yyyy/MM/dd"));
        model.setSoDT(txtSoDT.getText());
        model.setEmail(txtEmail.getText());
        model.setMaNV(txtMaNV.getText());
        model.setNgayDK(DateHelper.toDate(txtNgayDK.getText(), "yyyy/MM/dd"));
        model.setGhiChu(txtArena.getText());
        return model;
    }

    void setModel(NguoiHoc model) {
        txtMaNH.setText(model.getMaNH());
        txtHoten.setText(model.getHoTen());
        txtDiachi.setText(model.getDiachi());
        if (model.getGioitinh()) {
            rbtnNam.setSelected(true);
            rbtnNu.setSelected(false);
        } else {
            rbtnNam.setSelected(false);
            rbtnNu.setSelected(true);
        }
        txtNgayS.setText(DateHelper.toString(model.getNgaySinh(), "yyyy/MM/dd"));
        txtSoDT.setText(model.getSoDT());
        txtEmail.setText(model.getEmail());
        txtMaNV.setText(model.getMaNV());
        txtNgayDK.setText(DateHelper.toString(model.getNgayDK(), "yyyy/MM/dd"));
        txtArena.setText(model.getGhiChu());
    }

    void setStatus(boolean insertable) {
        btnThem.setEnabled(insertable);
        btnSua.setEnabled(!insertable);
        btnXoa.setEnabled(!insertable);

        boolean first = this.index > 0;
        boolean last = this.index < tblNguoiHoc.getRowCount() - 1;
        btnFirst.setEnabled(!insertable && first);
        btnPrev.setEnabled(!insertable && first);
        btnNext.setEnabled(!insertable && last);
        btnLast.setEnabled(!insertable && last);
    }

    void edit() {
        try {
            String manh = (String) tblNguoiHoc.getValueAt(this.index, 0);
            NguoiHoc modelnh = nhdao.findById(manh);
            if (modelnh != null) {
                setModel(modelnh);
                this.setStatus(false);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    boolean checkMaNH() {
        String ma = txtMaNH.getText();
        NguoiHoc nh = nhdao.findById(ma);
        if (txtMaNH.getText().length() == 7) {
            if (nh == null) {
                return true;
            } else {
                DialogHelper.alert(this, "Mã đã tồn tại");
                txtMaNH.requestFocus();
                return false;
            }
        } else {
            DialogHelper.alert(this, "Mã không được để trống và có 7 kí tự");
            txtMaNH.requestFocus();
            return false;
        }
    }

    boolean checkBirthDay() {
        NguoiHoc model = getModel();
        int yearS = model.getNgaySinh().getYear();
        int yearN = model.getNgayDK().getYear();
        int tong = yearN - yearS;
        if (tong >= 16) {
            return true;
        } else {
            DialogHelper.alert(this, "Chỉ cho phép người trên hoặc bằng 16 tuổi đăng ký");
            txtNgayS.requestFocus();
            return false;
        }
    }

    boolean checkGmail() {
        String email = "\\w+@+fpt+\\.+edu+\\.+vn+";
        if (txtEmail.getText().matches(email)) {
            return true;
        } else {
            DialogHelper.alert(this, "Không đúng định dạng email. Phải có @fpt.edu.vn");
            txtEmail.requestFocus();
            return false;
        }
    }
    
    boolean checkPhone() {
        String sdt = "0[0-9]{9,10}";
        if (txtSoDT.getText().matches(sdt)) {
            return true;
        } else {
            DialogHelper.alert(this, "Phải bắt đầu từ 0 và có 10 số");
            txtSoDT.requestFocus();
            return false;
        }
    }

}
