/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polypro.ui;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import polypro.dao.NhanVienDAO;
import polypro.helper.DialogHelper;
import polypro.helper.ShareHelper;
import polypro.model.NhanVien;

/**
 *
 * @author PC
 */
public class NhanVienJFrame extends javax.swing.JFrame {

    int index = 0;
    NhanVienDAO dao = new NhanVienDAO();

    /**
     * Creates new form NhanVienJFrame
     */
    public NhanVienJFrame() {
        initComponents();
        init();
    }

    void init() {
        tblNhanvien.setRowSelectionInterval(index, index);
        rbtnNam.setSelected(true);
        rbtnTP.setSelected(true);
        setStatus(true);
        load();
        setIconImage(ShareHelper.APP_ICON);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        LogoT = new javax.swing.JLabel();
        TitleTop = new javax.swing.JLabel();
        B1 = new javax.swing.JLabel();
        B2 = new javax.swing.JLabel();
        B3 = new javax.swing.JLabel();
        B4 = new javax.swing.JLabel();
        BtnExit = new javax.swing.JButton();
        pnlNhanVien = new javax.swing.JTabbedPane();
        pnlCapNhat = new javax.swing.JPanel();
        txtMaNV = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        rbtnNam = new javax.swing.JRadioButton();
        rbtnNu = new javax.swing.JRadioButton();
        rbtnTP = new javax.swing.JRadioButton();
        rbtnNV = new javax.swing.JRadioButton();
        txtSdt = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtMK2 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        pnlDanhSach = new javax.swing.JPanel();
        Spator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanvien = new javax.swing.JTable();
        BGRT = new javax.swing.JLabel();
        BGRB = new javax.swing.JLabel();
        BGLT = new javax.swing.JLabel();
        BGLB = new javax.swing.JLabel();
        BGButton = new javax.swing.JLabel();
        BGLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/icons8_java_48px.png"))); // NOI18N
        getContentPane().add(LogoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 100, 100));

        TitleTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/HỆ THỐNG QUẢN LÝ ĐÀO TẠO.png"))); // NOI18N
        getContentPane().add(TitleTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        B1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 10.png"))); // NOI18N
        B1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 300, -1));

        B2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 6.png"))); // NOI18N
        B2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        B3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 3.png"))); // NOI18N
        B3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        B4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        B4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 4.png"))); // NOI18N
        B4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        BtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/Left.png"))); // NOI18N
        BtnExit.setContentAreaFilled(false);
        BtnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 535, -1, 50));

        pnlNhanVien.setBackground(new java.awt.Color(0, 255, 51));
        pnlNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        pnlCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        pnlCapNhat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtMaNV.setForeground(new java.awt.Color(255, 0, 0));
        txtMaNV.setBorder(null);
        txtMaNV.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        pnlCapNhat.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 160, -1));

        txtHoten.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtHoten.setBorder(null);
        pnlCapNhat.add(txtHoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 210, -1));

        rbtnNam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbtnNam);
        rbtnNam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtnNam.setText("Nam");
        pnlCapNhat.add(rbtnNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, 20));

        rbtnNu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbtnNu);
        rbtnNu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtnNu.setText("Nữ");
        pnlCapNhat.add(rbtnNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, 20));

        rbtnTP.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnTP);
        rbtnTP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtnTP.setText("Trưởng phòng");
        pnlCapNhat.add(rbtnTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, 20));

        rbtnNV.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbtnNV);
        rbtnNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbtnNV.setText("Nhân viên");
        pnlCapNhat.add(rbtnNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, 20));

        txtSdt.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtSdt.setBorder(null);
        pnlCapNhat.add(txtSdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 160, -1));

        txtDiachi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtDiachi.setBorder(null);
        pnlCapNhat.add(txtDiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 210, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtEmail.setBorder(null);
        pnlCapNhat.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 210, -1));

        txtMK.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtMK.setForeground(new java.awt.Color(0, 0, 255));
        txtMK.setBorder(null);
        pnlCapNhat.add(txtMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 160, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Mã nhân viên:");
        pnlCapNhat.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Vai trò:");
        pnlCapNhat.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Họ và tên:");
        pnlCapNhat.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Giới tính:");
        pnlCapNhat.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Địa chỉ:");
        pnlCapNhat.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Email:");
        pnlCapNhat.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 50, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Số điện thoại:");
        pnlCapNhat.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Mật khẩu:");
        pnlCapNhat.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        pnlCapNhat.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 160, 10));
        pnlCapNhat.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 160, 10));
        pnlCapNhat.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 210, 10));
        pnlCapNhat.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 210, 10));
        pnlCapNhat.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 210, 10));
        pnlCapNhat.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 160, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Xác nhận mật khẩu:");
        pnlCapNhat.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtMK2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtMK2.setForeground(new java.awt.Color(0, 0, 255));
        txtMK2.setBorder(null);
        pnlCapNhat.add(txtMK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 160, -1));
        pnlCapNhat.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 160, 10));

        btnThem.setBackground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 17.png"))); // NOI18N
        btnThem.setBorder(null);
        btnThem.setContentAreaFilled(false);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        btnSua.setBackground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 18.png"))); // NOI18N
        btnSua.setBorder(null);
        btnSua.setContentAreaFilled(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 19.png"))); // NOI18N
        btnXoa.setBorder(null);
        btnXoa.setContentAreaFilled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 20.png"))); // NOI18N
        btnMoi.setBorder(null);
        btnMoi.setContentAreaFilled(false);
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 21.png"))); // NOI18N
        btnFirst.setBorder(null);
        btnFirst.setContentAreaFilled(false);
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 22.png"))); // NOI18N
        btnPrev.setBorder(null);
        btnPrev.setContentAreaFilled(false);
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnPrev, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 23.png"))); // NOI18N
        btnNext.setBorder(null);
        btnNext.setContentAreaFilled(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/Rectangle 24.png"))); // NOI18N
        btnLast.setBorder(null);
        btnLast.setContentAreaFilled(false);
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        pnlCapNhat.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        pnlNhanVien.addTab("Cập Nhật", pnlCapNhat);

        pnlDanhSach.setBackground(new java.awt.Color(255, 255, 255));
        pnlDanhSach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlDanhSach.add(Spator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 540, 10));

        tblNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Mật khẩu", "Họ tên", "Giới tính", "Email", "Số điện thoại", "Địa chỉ", "Vai trò"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanvien.setGridColor(new java.awt.Color(0, 0, 255));
        tblNhanvien.setSelectionBackground(new java.awt.Color(0, 0, 255));
        tblNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanvien);

        pnlDanhSach.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 591, 350));

        pnlNhanVien.addTab("Danh Sách", pnlDanhSach);

        getContentPane().add(pnlNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 620, 440));

        BGRT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BGRT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 7.png"))); // NOI18N
        getContentPane().add(BGRT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        BGRB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BGRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 8.png"))); // NOI18N
        getContentPane().add(BGRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, -1, 30));

        BGLT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 1.png"))); // NOI18N
        BGLT.setToolTipText("");
        getContentPane().add(BGLT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BGLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BGLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 11.png"))); // NOI18N
        getContentPane().add(BGLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 530, 320, 60));

        BGButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BGButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 9.png"))); // NOI18N
        getContentPane().add(BGButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 300, 390));

        BGLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 5.png"))); // NOI18N
        getContentPane().add(BGLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 660, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
        // TODO add your handling code here:
        new MainFrame().setEnabled(true);
    }//GEN-LAST:event_B1MouseClicked

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        // TODO add your handling code here:
        back();
    }//GEN-LAST:event_BtnExitActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        if (checkMaNV() && checkMK() && checkHT() && checkPhone() && checkGmail()) {
            insert();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        try {
            if (checkMK() && checkHT() && checkGmail() && checkPhone()) {
                update();
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Không được nhập số âm");
        }


    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void tblNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanvienMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            index = tblNhanvien.rowAtPoint(evt.getPoint());
            if (index >= 0) {
                txtMaNV.setEnabled(false);
                edit();
                pnlNhanVien.setSelectedIndex(0);
            }
        }

    }//GEN-LAST:event_tblNhanvienMouseClicked

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        this.index++;
        this.edit();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        this.index = 0;
        this.edit();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        this.index--;
        this.edit();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        this.index = tblNhanvien.getRowCount() - 1;
        this.edit();
    }//GEN-LAST:event_btnLastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel B1;
    private javax.swing.JLabel B2;
    private javax.swing.JLabel B3;
    private javax.swing.JLabel B4;
    private javax.swing.JLabel BGButton;
    private javax.swing.JLabel BGLB;
    private javax.swing.JLabel BGLT;
    private javax.swing.JLabel BGLogo;
    private javax.swing.JLabel BGRB;
    private javax.swing.JLabel BGRT;
    private javax.swing.JButton BtnExit;
    private javax.swing.JLabel LogoT;
    private javax.swing.JSeparator Spator2;
    private javax.swing.JLabel TitleTop;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel pnlCapNhat;
    private javax.swing.JPanel pnlDanhSach;
    private javax.swing.JTabbedPane pnlNhanVien;
    private javax.swing.JRadioButton rbtnNV;
    private javax.swing.JRadioButton rbtnNam;
    private javax.swing.JRadioButton rbtnNu;
    private javax.swing.JRadioButton rbtnTP;
    private javax.swing.JTable tblNhanvien;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMK;
    private javax.swing.JTextField txtMK2;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSdt;
    // End of variables declaration//GEN-END:variables

    void load() {
        DefaultTableModel model = (DefaultTableModel) tblNhanvien.getModel();
        model.setRowCount(0);
        try {
            List<NhanVien> listNV = dao.Select();
            for (NhanVien nv : listNV) {
                Object[] row = {
                    nv.getMaNV(),
                    nv.getMatkhau(),
                    nv.getHoten(),
                    nv.getGioitinh() ? "Nam" : "Nữ",
                    nv.getEmail(),
                    nv.getSoDT(),
                    nv.getDiachi(),
                    nv.getVaitro() ? "Trưởng phòng" : "Nhân viên"
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "LOAD DỮ LIỆU LỖI!!");
        }

    }

    void clear() {
        txtMaNV.setEnabled(true);
        txtMaNV.setText("");
        txtHoten.setText("");
        txtMK.setText("");
        txtMK2.setText("");
        txtEmail.setText("");
        txtSdt.setText("");
        txtDiachi.setText("");
        rbtnNam.setSelected(true);
        rbtnTP.setSelected(true);
        btnThem.setEnabled(true);
        setStatus(true);
    }

    void back() {
        this.dispose();
    }

    void insert() {
        NhanVien model = getModel();
        String confirm = txtMK2.getText();
        if (confirm.equals(model.getMatkhau())) {
            try {
                dao.Insert(model);
                load();
                clear();
                DialogHelper.alert(this, "Thêm nhân viên thành công");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            DialogHelper.alert(this, "Xác nhận mật khẩu không đúng!");
        }

    }

    void update() {
        NhanVien model = getModel();
        String confirm = txtMK2.getText();
        if (confirm.equals(model.getMatkhau())) {
            try {
                dao.Update(model);
                load();
                clear();
                DialogHelper.alert(this, "Cập nhật thông tin nhân viên thành công");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            DialogHelper.alert(this, "Mật khẩu và Mật khẩu xác nhận phải giống nhau");
        }
    }

    void delete() {
        if (DialogHelper.confirm(this, "Bạn có muốn xoá nhân viên này?")) {
            String manv = txtMaNV.getText();
            if (manv != null) {
                try {
                    dao.Delete(manv);
                    load();
                    clear();
                    DialogHelper.alert(this, "Xoá nhân viên thành công");
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {

            }
        }

    }

    NhanVien getModel() {
        NhanVien model = new NhanVien();
        model.setMaNV(txtMaNV.getText());
        model.setMatkhau(txtMK.getText());
        model.setHoten(txtHoten.getText());
        model.setGioitinh(rbtnNam.isSelected());
        model.setEmail(txtEmail.getText());
        model.setSoDT(txtSdt.getText());
        model.setDiachi(txtDiachi.getText());
        model.setVaitro(rbtnTP.isSelected());
        return model;
    }

    void setModel(NhanVien model) {
        txtMaNV.setText(model.getMaNV());
        txtMK.setText(model.getMatkhau());
        txtMK2.setText(model.getMatkhau());
        txtHoten.setText(model.getHoten());
        if (model.getGioitinh()) {
            rbtnNam.setSelected(true);
            rbtnNu.setSelected(false);
        } else {
            rbtnNam.setSelected(false);
            rbtnNu.setSelected(true);
        }
        txtEmail.setText(model.getEmail());
        txtSdt.setText(model.getSoDT());
        txtDiachi.setText(model.getDiachi());
        if (model.getVaitro()) {
            rbtnTP.setSelected(true);
            rbtnNV.setSelected(false);
        } else {
            rbtnTP.setSelected(false);
            rbtnNV.setSelected(true);
        }

    }

    void setStatus(boolean insertable) {
        btnThem.setEnabled(insertable);
        btnSua.setEnabled(!insertable);
        btnXoa.setEnabled(!insertable);

        boolean first = this.index > 0;
        boolean last = this.index < tblNhanvien.getRowCount() - 1;
        btnFirst.setEnabled(!insertable && first);
        btnPrev.setEnabled(!insertable && first);
        btnNext.setEnabled(!insertable && last);
        btnLast.setEnabled(!insertable && last);
    }

    void edit() {
        try {
            String manv = (String) tblNhanvien.getValueAt(this.index, 0);
            NhanVien model = dao.findByID(manv);
            if (model != null) {
                setModel(model);
                this.setStatus(false);
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    boolean checkMaNV() {
        String ma = txtMaNV.getText();
        NhanVien nv = dao.findByID(ma);
        if (txtMaNV.getText().length() == 0 || nv != null) {
            DialogHelper.alert(this, "Mã không được để trống hoặc đã tồn tại!!");
            txtMaNV.requestFocus();
            return false;
        }
        return true;
    }

    boolean checkMK() {
        if (txtMK.getText().length() < 3) {
            DialogHelper.alert(this, "Mật khẩu phải ít nhất 3 kí tự");
            txtMK.requestFocus();
            return false;
        }
        if (txtMK2.getText().equals(txtMK.getText())) {
            txtMK2.requestFocus();
            return true;
        } else {
            DialogHelper.alert(this, "Mật khẩu xác nhận phải giống mật khẩu");
        }
        return true;
    }

    boolean checkHT() {
        String ht = "[a-zA-Z  ]+ ";
        if (txtHoten.getText().equals("")) {
            DialogHelper.alert(this, "Họ tên không được để trống");
            txtHoten.requestFocus();
            return false;
        }else if (txtHoten.getText().matches("[a-zA-Z  ]+ ")) {
            DialogHelper.alert(this, "Họ tên chỉ được nhập chữ");
            txtHoten.requestFocus();
            return false;
        }
        return true;
    }

    boolean checkGmail() {
        String email = "\\w+@+fpt+\\.+edu+\\.+vn+";
        if (txtEmail.getText().matches(email)) {
            return true;
        } else {
            DialogHelper.alert(this, "Không đúng định dạng email. Phải có @fpt.edu.vn");
            txtEmail.requestFocus();
            return false;
        }
    }

    boolean checkPhone() {
        String sdt = "0[0-9]{9,10}";
        if (txtSdt.getText().matches(sdt)) {
            return true;
        } else {
            DialogHelper.alert(this, "Phải bắt đầu từ 0 và có 10 số");
            txtSdt.requestFocus();
            return false;
        }
    }
}
