/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polypro.ui;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import polypro.dao.KhoaHocDAO;
import polypro.dao.ThongKeDAO;
import polypro.helper.ShareHelper;
import polypro.model.KhoaHoc;

/**
 *
 * @author PC
 */
public class TableThongKeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TableThongKeJFrame
     */
    public TableThongKeJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDoanhThu = new javax.swing.JTabbedPane();
        pnlNH = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguoihoc = new javax.swing.JTable();
        pnlBD = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBangdiem = new javax.swing.JTable();
        cboKhoaHoc = new javax.swing.JComboBox<>();
        btnBangdiem = new javax.swing.JButton();
        lblKhoahoc = new javax.swing.JLabel();
        pnlTHD = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTonghopdiem = new javax.swing.JTable();
        pnlDT = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDoanhthu = new javax.swing.JTable();
        lblNam = new javax.swing.JLabel();
        cboDoanhthu = new javax.swing.JComboBox<>();
        btnDoanhthu = new javax.swing.JButton();
        LogoT = new javax.swing.JLabel();
        TitleTop = new javax.swing.JLabel();
        btnThongke = new javax.swing.JLabel();
        btnQuanly = new javax.swing.JLabel();
        btnHuongdan = new javax.swing.JLabel();
        btnDangxuat = new javax.swing.JLabel();
        BtnExit = new javax.swing.JButton();
        BGRT = new javax.swing.JLabel();
        BGRB = new javax.swing.JLabel();
        BGLT = new javax.swing.JLabel();
        BGLB = new javax.swing.JLabel();
        BGButton = new javax.swing.JLabel();
        BGLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        pnlDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        pnlNH.setBackground(new java.awt.Color(255, 255, 255));
        pnlNH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNguoihoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Năm", "Số người học", "Đầu tiên", "Sau cùng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNguoihoc);

        pnlNH.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 591, 365));

        pnlDoanhThu.addTab("NGƯỜI HỌC", pnlNH);

        pnlBD.setBackground(new java.awt.Color(255, 255, 255));
        pnlBD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBangdiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã NH", "Họ tên", "Điểm", "Xếp loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblBangdiem);

        pnlBD.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 68, 591, 303));

        cboKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhoaHocActionPerformed(evt);
            }
        });
        pnlBD.add(cboKhoaHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 13, 350, 30));

        btnBangdiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/icons8_search_database_100px.png"))); // NOI18N
        btnBangdiem.setContentAreaFilled(false);
        pnlBD.add(btnBangdiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, -1, -1, 60));

        lblKhoahoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKhoahoc.setText("Khoá học:");
        pnlBD.add(lblKhoahoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        pnlDoanhThu.addTab("BẢNG ĐIỂM", pnlBD);

        pnlTHD.setBackground(new java.awt.Color(255, 255, 255));
        pnlTHD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTonghopdiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Chuyên đề", "Tổng số HV", "Cao nhất", "Thấp nhất", "Trung bình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblTonghopdiem);

        pnlTHD.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 591, 358));

        pnlDoanhThu.addTab("TỔNG HỢP ĐIỂM", pnlTHD);

        pnlDT.setBackground(new java.awt.Color(255, 255, 255));
        pnlDT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDoanhthu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Chuyên đề", "Số khoá", "Số HV", "Doanh thu", "HP cao nhất", "HP thấp nhất", "HP trung bình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblDoanhthu);

        pnlDT.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 68, 590, 303));

        lblNam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNam.setText("Năm:");
        pnlDT.add(lblNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 30));

        cboDoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDoanhthuActionPerformed(evt);
            }
        });
        pnlDT.add(cboDoanhthu, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 13, 350, 30));

        btnDoanhthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/NguoiHoc/icons8_search_database_100px.png"))); // NOI18N
        btnDoanhthu.setContentAreaFilled(false);
        pnlDT.add(btnDoanhthu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, -1, -1, 60));

        pnlDoanhThu.addTab("DOANH THU", pnlDT);

        getContentPane().add(pnlDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 620, 430));

        LogoT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/icons8_java_48px.png"))); // NOI18N
        getContentPane().add(LogoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 100, 100));

        TitleTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/HỆ THỐNG QUẢN LÝ ĐÀO TẠO.png"))); // NOI18N
        getContentPane().add(TitleTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        btnThongke.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 10.png"))); // NOI18N
        btnThongke.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongkeMouseClicked(evt);
            }
        });
        getContentPane().add(btnThongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 300, -1));

        btnQuanly.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnQuanly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 6.png"))); // NOI18N
        btnQuanly.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnQuanly, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        btnHuongdan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 3.png"))); // NOI18N
        btnHuongdan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnHuongdan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        btnDangxuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 4.png"))); // NOI18N
        btnDangxuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnDangxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        BtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/Left.png"))); // NOI18N
        BtnExit.setContentAreaFilled(false);
        BtnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnExitMouseClicked(evt);
            }
        });
        getContentPane().add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 535, -1, 50));

        BGRT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BGRT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 7.png"))); // NOI18N
        getContentPane().add(BGRT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        BGRB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BGRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 8.png"))); // NOI18N
        getContentPane().add(BGRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, -1, 30));

        BGLT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 1.png"))); // NOI18N
        BGLT.setToolTipText("");
        getContentPane().add(BGLT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BGLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BGLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 11.png"))); // NOI18N
        getContentPane().add(BGLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 530, 320, 60));

        BGButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BGButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 9.png"))); // NOI18N
        getContentPane().add(BGButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 300, 390));

        BGLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/polypro/icon/img/Main/Rectangle 5.png"))); // NOI18N
        getContentPane().add(BGLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 660, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeMouseClicked
        // TODO add your handling code here:
        new MainFrame().setEnabled(true);

    }//GEN-LAST:event_btnThongkeMouseClicked

    private void BtnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtnExitMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        fillComboBoxKhoaHoc();
        fillTableBangDiem();
        fillTableNguoiHoc();
        fillTableKhoaHoc();
        fillComboBoxNam();
        fillTableDoanhThu();
    }//GEN-LAST:event_formWindowOpened

    private void cboKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhoaHocActionPerformed
        // TODO add your handling code here:
        fillTableBangDiem();
    }//GEN-LAST:event_cboKhoaHocActionPerformed

    private void cboDoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDoanhthuActionPerformed
        // TODO add your handling code here:
        fillTableDoanhThu();
    }//GEN-LAST:event_cboDoanhthuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableThongKeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableThongKeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGButton;
    private javax.swing.JLabel BGLB;
    private javax.swing.JLabel BGLT;
    private javax.swing.JLabel BGLogo;
    private javax.swing.JLabel BGRB;
    private javax.swing.JLabel BGRT;
    private javax.swing.JButton BtnExit;
    private javax.swing.JLabel LogoT;
    private javax.swing.JLabel TitleTop;
    private javax.swing.JButton btnBangdiem;
    private javax.swing.JLabel btnDangxuat;
    private javax.swing.JButton btnDoanhthu;
    private javax.swing.JLabel btnHuongdan;
    private javax.swing.JLabel btnQuanly;
    private javax.swing.JLabel btnThongke;
    private javax.swing.JComboBox<String> cboDoanhthu;
    private javax.swing.JComboBox<String> cboKhoaHoc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblKhoahoc;
    private javax.swing.JLabel lblNam;
    private javax.swing.JPanel pnlBD;
    private javax.swing.JPanel pnlDT;
    private javax.swing.JTabbedPane pnlDoanhThu;
    private javax.swing.JPanel pnlNH;
    private javax.swing.JPanel pnlTHD;
    private javax.swing.JTable tblBangdiem;
    private javax.swing.JTable tblDoanhthu;
    private javax.swing.JTable tblNguoihoc;
    private javax.swing.JTable tblTonghopdiem;
    // End of variables declaration//GEN-END:variables

    ThongKeDAO dao = new ThongKeDAO();
    KhoaHocDAO khdao = new KhoaHocDAO();

    void init() {
        setIconImage(ShareHelper.APP_ICON);
        setLocationRelativeTo(null);
    }

    void fillComboBoxKhoaHoc() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboKhoaHoc.getModel();
        model.removeAllElements();

        List<KhoaHoc> list = khdao.Select();
        for (KhoaHoc kh : list) {
            model.addElement(kh);
        }

        cboKhoaHoc.setSelectedIndex(0);
    }

    void fillComboBoxNam() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboDoanhthu.getModel();
        model.removeAllElements();

        List<KhoaHoc> list = khdao.Select();
        for (KhoaHoc kh : list) {
            int nam = kh.getNgayKG().getYear() + 1900;
            if (model.getIndexOf(nam) < 0) {
                model.addElement(nam);
            }
        }

        cboDoanhthu.setSelectedIndex(0);
    }

    void fillTableBangDiem() {
        DefaultTableModel model = (DefaultTableModel) tblBangdiem.getModel();
        model.setRowCount(0);

        KhoaHoc kh = (KhoaHoc) cboKhoaHoc.getSelectedItem();
        List<Object[]> list = dao.getBangDiem(kh.getMaKH());
        for (Object[] row : list) {
            model.addRow(row);
        }
    }

    void fillTableNguoiHoc() {
        DefaultTableModel model = (DefaultTableModel) tblNguoihoc.getModel();
        model.setRowCount(0);

        List<Object[]> list = dao.getNguoiHoc();
        for (Object[] row : list) {
            model.addRow(row);
        }
    }

    void fillTableKhoaHoc() {
        DefaultTableModel model = (DefaultTableModel) tblTonghopdiem.getModel();
        model.setRowCount(0);

        List<Object[]> list = dao.getDiemTheoChuyenDe();
        for (Object[] row : list) {
            model.addRow(row);
        }
    }

    void fillTableDoanhThu() {
        DefaultTableModel model = (DefaultTableModel) tblDoanhthu.getModel();
        model.setRowCount(0);
        int nam = Integer.parseInt(cboDoanhthu.getSelectedItem().toString());
        List<Object[]> list = dao.getDoanhThu(nam);
        for (Object[] row : list) {
            model.addRow(row);
        }
    }
}
